#pragma once
#include <winioctl.h>
#include <winnt.h>

#define IOCTL_STACK_OVERFLOW CTL_CODE(FILE_DEVICE_UNKNOWN, 0x800, METHOD_NEITHER, FILE_ANY_ACCESS);
#define IOCTL_INTEGER_OVERFLOW 2236455
#define IOCTL_WRITE_WHAT_WHERE 2236427
#define IOCTL_NULL_POINTER_DEREFERENCE 2236459